spring.application.name=connect-four-ai
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
spring.web.error.include-binding-errors=always
logging.level.org.springframework.web.servlet.view=DEBUG